---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ job_k8s_namespace }}
  name: {{ resource_name }}
  labels:
    app: {{ job_k8s_namespace }}
    racetrack/job: {{ resource_name }}
    racetrack/job-name: {{ job_name }}
    racetrack/job-version: {{ job_version }}
data:
  git_credentials: "{{ git_credentials }}"
  secret_build_env: "{{ secret_build_env }}"
  secret_runtime_env: "{{ secret_runtime_env }}"
